// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6DJkPmHY5SLmKWFpAEwtam
// Component: lZJgYgKoU6i
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import UploadAvatar from "../../UploadAvatar"; // plasmic-import: 9xuliDXofB/component
import TextInput from "../../TextInput"; // plasmic-import: I_rUXdtei71/component
import Button from "../../Button"; // plasmic-import: lcgmPEWIbZ9/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_whats_up_clone.module.css"; // plasmic-import: 6DJkPmHY5SLmKWFpAEwtam/projectcss
import sty from "./PlasmicUserProfile.module.css"; // plasmic-import: lZJgYgKoU6i/css

import SearchsvgIcon from "./icons/PlasmicIcon__Searchsvg"; // plasmic-import: B02IfxOijYJ/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: F6EIEztEldC/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: WmT0SVOtYXf/icon

export type PlasmicUserProfile__VariantMembers = {
  isError: "isError";
};

export type PlasmicUserProfile__VariantsArgs = {
  isError?: SingleBooleanChoiceArg<"isError">;
};

type VariantPropType = keyof PlasmicUserProfile__VariantsArgs;
export const PlasmicUserProfile__VariantProps = new Array<VariantPropType>(
  "isError"
);

export type PlasmicUserProfile__ArgsType = {
  errorMessage?: React.ReactNode;
};

type ArgPropType = keyof PlasmicUserProfile__ArgsType;
export const PlasmicUserProfile__ArgProps = new Array<ArgPropType>(
  "errorMessage"
);

export type PlasmicUserProfile__OverridesType = {
  root?: p.Flex<"div">;
  text?: p.Flex<"div">;
  uploadAvatar?: p.Flex<typeof UploadAvatar>;
  firstNameInput?: p.Flex<typeof TextInput>;
  lastNameInput?: p.Flex<typeof TextInput>;
  updateProfileButton?: p.Flex<typeof Button>;
  button?: p.Flex<typeof Button>;
};

export interface DefaultUserProfileProps {
  errorMessage?: React.ReactNode;
  isError?: SingleBooleanChoiceArg<"isError">;
  className?: string;
}

function PlasmicUserProfile__RenderFunc(props: {
  variants: PlasmicUserProfile__VariantsArgs;
  args: PlasmicUserProfile__ArgsType;
  overrides: PlasmicUserProfile__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        { [sty.rootisError]: hasVariant(variants, "isError", "isError") }
      )}
    >
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"Update profile"}
      </div>

      <UploadAvatar
        data-plasmic-name={"uploadAvatar"}
        data-plasmic-override={overrides.uploadAvatar}
        className={classNames("__wab_instance", sty.uploadAvatar)}
      />

      <TextInput
        data-plasmic-name={"firstNameInput"}
        data-plasmic-override={overrides.firstNameInput}
        className={classNames("__wab_instance", sty.firstNameInput, {
          [sty.firstNameInputisError]: hasVariant(
            variants,
            "isError",
            "isError"
          )
        })}
        placeholder={"Enter your firstname" as const}
        type={"text" as const}
      />

      <TextInput
        data-plasmic-name={"lastNameInput"}
        data-plasmic-override={overrides.lastNameInput}
        className={classNames("__wab_instance", sty.lastNameInput, {
          [sty.lastNameInputisError]: hasVariant(variants, "isError", "isError")
        })}
        placeholder={"Enter your lastname" as const}
        type={"text" as const}
      />

      <Button
        data-plasmic-name={"updateProfileButton"}
        data-plasmic-override={overrides.updateProfileButton}
        className={classNames("__wab_instance", sty.updateProfileButton, {
          [sty.updateProfileButtonisError]: hasVariant(
            variants,
            "isError",
            "isError"
          )
        })}
        color={"softGreen" as const}
      >
        {"Save profile"}
      </Button>

      <Button
        data-plasmic-name={"button"}
        data-plasmic-override={overrides.button}
        className={classNames("__wab_instance", sty.button, {
          [sty.buttonisError]: hasVariant(variants, "isError", "isError")
        })}
        color={"link" as const}
        link={`/`}
      >
        {"Let's chat !"}
      </Button>

      {(hasVariant(variants, "isError", "isError") ? true : true) ? (
        <div
          className={classNames(projectcss.all, sty.freeBox__xJSd, {
            [sty.freeBoxisError__xJSDa5ZpF]: hasVariant(
              variants,
              "isError",
              "isError"
            )
          })}
        >
          <div
            className={classNames(projectcss.all, sty.freeBox__srdZx, {
              [sty.freeBoxisError__srdZxa5ZpF]: hasVariant(
                variants,
                "isError",
                "isError"
              )
            })}
          >
            {p.renderPlasmicSlot({
              defaultContents: "Enter some text",
              value: args.errorMessage,
              className: classNames(sty.slotTargetErrorMessage, {
                [sty.slotTargetErrorMessageisError]: hasVariant(
                  variants,
                  "isError",
                  "isError"
                )
              })
            })}
          </div>
        </div>
      ) : null}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "text",
    "uploadAvatar",
    "firstNameInput",
    "lastNameInput",
    "updateProfileButton",
    "button"
  ],
  text: ["text"],
  uploadAvatar: ["uploadAvatar"],
  firstNameInput: ["firstNameInput"],
  lastNameInput: ["lastNameInput"],
  updateProfileButton: ["updateProfileButton"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  text: "div";
  uploadAvatar: typeof UploadAvatar;
  firstNameInput: typeof TextInput;
  lastNameInput: typeof TextInput;
  updateProfileButton: typeof Button;
  button: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicUserProfile__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicUserProfile__VariantsArgs;
    args?: PlasmicUserProfile__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicUserProfile__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicUserProfile__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicUserProfile__ArgProps,
          internalVariantPropNames: PlasmicUserProfile__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicUserProfile__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUserProfile";
  } else {
    func.displayName = `PlasmicUserProfile.${nodeName}`;
  }
  return func;
}

export const PlasmicUserProfile = Object.assign(
  // Top-level PlasmicUserProfile renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),
    uploadAvatar: makeNodeComponent("uploadAvatar"),
    firstNameInput: makeNodeComponent("firstNameInput"),
    lastNameInput: makeNodeComponent("lastNameInput"),
    updateProfileButton: makeNodeComponent("updateProfileButton"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicUserProfile
    internalVariantProps: PlasmicUserProfile__VariantProps,
    internalArgProps: PlasmicUserProfile__ArgProps
  }
);

export default PlasmicUserProfile;
/* prettier-ignore-end */
